import { Factory, Seeder } from 'typeorm-seeding';
import { Connection } from 'typeorm';
import { v4 as uuid } from 'uuid';
import { Ingredient } from '../../models/Ingredients';

const IngredientsSeedData = [
  {
    id: uuid(),
    name: 'Leite',
    isVegan: false,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Soro de leite',
    isVegan: false,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Proteína do soro de leite',
    isVegan: false,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Caseína',
    isVegan: false,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Albumina',
    isVegan: false,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Corante cochonilha',
    isVegan: false,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Mel',
    isVegan: false,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Geléia real',
    isVegan: false,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Própolis',
    isVegan: false,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Colágeno',
    isVegan: false,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Gelatina',
    isVegan: false,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Glicerol',
    isVegan: false,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Lactose',
    isVegan: false,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Lecitina',
    isVegan: false,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Cocotó',
    isVegan: false,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Queratina',
    isVegan: false,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Quitosana',
    isVegan: false,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Tirosina',
    isVegan: false,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Tutano',
    isVegan: false,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Ovo',
    isVegan: false,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Clara de ovo',
    isVegan: false,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Gema',
    isVegan: false,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Manteiga',
    isVegan: false,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Banha de porco',
    isVegan: false,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Óleo de peixe',
    isVegan: false,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Vitamina D3',
    isVegan: false,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Aromas naturais',
    isVegan: false,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Carne',
    isVegan: false,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Ovos e mel',
    isVegan: false,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Mocotó',
    isVegan: false,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
];

export default class CreateIngredients implements Seeder {
  public async run(factory: Factory, connection: Connection): Promise<any> {
    await connection
      .createQueryBuilder()
      .insert()
      .into(Ingredient)
      .values(IngredientsSeedData)
      .execute();
  }
}
