import { Factory, Seeder } from 'typeorm-seeding';
import { Connection } from 'typeorm';
import { v4 as uuid } from 'uuid';
import { Ingredient } from '../../models/Ingredients';

const IngredientsSeedData = [
  {
    id: uuid(),
    name: 'Água',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Acesulfame',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Acesulfame de Potássio',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Acesulfame K',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Ace K',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Ácido ascórbico',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Vitamina C',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Ácido benzóico',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Ácido carbônico',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Ácido cinâmico',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Ácido cítrico',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Ácido clorídrico',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Ácido eritórbico',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Ácido fólico',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Folato',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Vitamina B9',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Ácido fosfórico',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Ácido láurico',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Ácido málico',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Ácido salicílico',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Ácido sórbico',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Ácido sulfúrico',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Ácido tartárico',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Actinidina',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Açafrão',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Açúcar de Beterraba',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Açúcar de Cana',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Açúcar de coco',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Açúcar invertido',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Ágar-ágar (ágar)',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Álcool cetílico vegetal',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Ácido esteárico vegetal',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Álcool láurico ou Dodecanol',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Álcool metílico',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'ácido glicólico',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Alginato de Sódio',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Aloe vera',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Amaranto em grãos',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Amaranto em flocos',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Amêndoas',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Farinha de amêndoas',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Pasta de amêndoas',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Farinha de amaranto',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Amendoim',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Pasta de amendoim',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Amendoim em pó',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Proteína de amendoim',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Amido',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Amido ceroso',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Amido de milho',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Amido modificado',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Antocianinas',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Aroma natural',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Aroma artificial',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Arroz',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Arroz integral',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Arroz negro',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Arroz selvagem',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Arroz vermelho',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Proteína isolada de arroz',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Proteína concentrada de arroz',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Aspartame',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Aveia em grãos',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Aveia em flocos',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Aveia em flocos finos',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Aveia em flocos grossos',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Farinha de aveia',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Farelo de aveia',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Avelã',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Pasta de avelã',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Ashwagandha',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Azeite',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Azeite trufado',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Azeite de dendê',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Baunilha',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Bauxita',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Benzoato de Sódio',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Beta Caroteno',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Betatene',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Bicarbonato de Sódio',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Bicarbonato de Amônio',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Bitartarato de Potássio',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Cremor de tártaro',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Hidrogeno tartarato de Potássio',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Bromelina',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Butano',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Calcário',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Calciferol (vitamina D de origem vegetal)',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Cálcio Dissódico EDTA',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Canela',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Cacau',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Carbonato de Cálcio',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Carbonato de Sódio',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Carboximetilcelulose',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Caroteno',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Carvão',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Carvão vegetal (coco)',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Castanha de caju',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Castanha do pará',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Castanha de baru',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Celulose',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Cera de Candelilla',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Cera de Carnaúba',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Cianocobalamina',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Ciclamato',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Ciclamato de Sódio',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Cinamato de metila',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Cloreto de Cálcio',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Cloreto de metila (clorometano)',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Cloreto de Potássio',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Cloreto de Sódio',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Cloridrato de Tiamina',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Cravo',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'ColFlo 67',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Cogumelos',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Colorau',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Cominho',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Corante caramelo',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Crospovidona',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Cúrcuma',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Curcumina',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Curry',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Dextrina',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'DihidroxiAcetona',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Dióxido de enxofre',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Estévia',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Stevia',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Esteviosídeo',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Glicosídeo de esteviol',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Eritritol',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Ervilha',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Proteína isolada de ervilha',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Proteína concentrada de ervilha',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Feijão preto',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Feijão carioca',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Feijão vermelho',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Feijão roxo',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Feijão jalo',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Feijão branco',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Feijão de corda',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Feijão moyashi',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Feno grego',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Fenol',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Fermento de pão',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Ferro',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Ferro de Redução Direta (FRD)',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Ferro reduzido',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Ferro-esponja',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Fécula de mandioca',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Farinha de mandioca',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Farinha de arroz',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Farinha sem glúten',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Ficina',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Fosfato de Sódio (mono-, di- e tri-)',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Frutose (xarope)',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Glutamato de monossódio (GMS)',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Glucose de milho',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Gordura vegetal',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Goma arábica',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Goma acácia',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Goma carragena',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Goma xantana',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Goma guar',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Grão-de-bico',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Farinha de grão de bico',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Hidróxido de Alumínio',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Hidróxido de Cálcio',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Hidróxido de Potássio',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Hidróxido de Sódio',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Hidroxipropil celulose',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Hidroxipropilmetilcelulose (HPMC)',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Hummus',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Inulina',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Isomerato de glicose',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Lactase',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Lauril Éter Sulfato de Sódio (LESS)',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Lauril Sulfato de Sódio (LSS)',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Bebida vegetal de soja',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Bebida vegetal de amêndoas',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Bebida vegetal de coco',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Bebida vegetal de castanha',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Bebida vegetal de aveia',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Bebida vegetal de soja',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Levedura',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Levedura nutricional',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Levedura de cerveja',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Lipoxigenase',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Louro',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Maca peruana',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Matchá',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Malte',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Maltitol',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Maltodextrina',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Maltose',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Manitol (Mannite)',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Manteiga de coco',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Manteiga de cacau',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Melado de cana',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Mel de cacau',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Menta',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Metabissulfito de Sódio',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Metafolin',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Metanol',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Metilcelulose',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Metilcobalamina',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Metoxicinamato de octila',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Milho',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Missô',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Monolaurato de sorbitana',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Mononitrato de tiamina',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Monopalmitato de sorbitana',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Nibs de cacau',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Noz moscada',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'NutraSweet',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Octinoxato',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Óleo de algodão',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Óleo de soja',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Óleo de coco',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Óleo de girassol',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Óleo de canola',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Óleo de linhaça',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Óleo de abacate',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Óleo de palma',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Óleo de rícino ou de mamona',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Óleo mineral branco',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Óleo vegetal',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Oxibenzona',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Papaína',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Páprica doce',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Páprica picante',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Páprica defumada',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Painço',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Pimenta',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Pectina',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Pirofosfato de Sódio',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Pirofosfato tetrassódico',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Fosfato de tetrasSódio',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Polvilho doce',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Polvilho azedo',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Propilparabeno',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Psyllium',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Quinoa em grãos',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Quinoa em flocos',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Farinha de quinoa',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Retinol (origem vegetal)',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Semente de abóbora',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Semente de girassol',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Semente de linhaça dourada',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Semente de linhaça marrom',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Semente de gergelim',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Semente de chia',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Semente de cânhamo',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Sucarina',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Soja em grãos',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Proteína texturizada de soja',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Farinha de soja',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Proteína isolada de soja',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Sorbato de Potássio',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Sorbitol',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Sucralose',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Sulfato de Alumínio de Sódio',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Sulfato de Sódio',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Sulfato ferroso',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Sunete',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Tahine',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Terbutil Hidroquinona (TBHQ)',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Butil Hidroquinona Terciária',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Tempeh',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Tocoferóis',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Tofu',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Tolueno',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Trigo',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Farelo de trigo',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Farinha de trigo',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Farinha de trigo sarraceno',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Farinha de sorgo',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Sorgo',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Trigo sarraceno',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Farinha de glúten',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Tumérico',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Vinagre de limão',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Vinagre de maçã',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Vinagre de arroz',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Vitamina C',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Vitamina E',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Xarope de milho',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Xarope de milho de alta frutose (XMAF)',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Xarope de bordô',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Xylitol',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Xilitol',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
  {
    id: uuid(),
    name: 'Zahtar',
    isVegan: true,
    enabled: true,
    createdAt: `${new Date()}`,
    updatedAt: `${new Date()}`,
  },
];

export default class CreateVeganIngredients implements Seeder {
  public async run(factory: Factory, connection: Connection): Promise<any> {
    const ingredientsSeed = IngredientsSeedData.map(el => {
      return {
        ...el,
        key: el.name
          .normalize('NFD')
          .replace(/[^a-zA-Zs]/g, '')
          .toUpperCase(),
      };
    });

    await connection
      .createQueryBuilder()
      .insert()
      .into(Ingredient)
      .values(ingredientsSeed)
      .execute();
  }
}
